<template>
  <h2>Capitulo primo</h2>
  Praesent consectetur fringilla felis, sit amet finibus dolor gravida id. Maecenas venenatis magna eget libero ullamcorper, in feugiat dolor venenatis. Donec posuere tempus ultricies. Donec condimentum semper nunc. Phasellus sed varius lorem. Morbi urna felis, faucibus a viverra quis, gravida non velit. Praesent sed consectetur libero, ac molestie nunc. Maecenas ac arcu eu metus pretium porttitor non eu purus. Nullam at odio vehicula, vulputate tortor in, aliquet mauris. Phasellus egestas metus nulla, ac convallis lacus pretium sed. Suspendisse vel imperdiet sapien. Sed condimentum, lectus non aliquam pellentesque, magna nibh porttitor eros, fermentum luctus felis lectus id nunc. Nulla facilisi. Etiam auctor sem sit amet enim cursus scelerisque ut et arcu. Cras vel dignissim nisi, vel blandit lectus. Pellentesque sed dignissim nisl, sed sodales dolor. <br><br>

  Suspendisse feugiat vehicula semper. Nunc nec molestie lacus. Curabitur in risus augue. Etiam nec ligula rhoncus, commodo elit quis, aliquet tellus. In aliquam imperdiet dolor, ut scelerisque eros gravida malesuada. Integer mauris justo, pharetra nec sem et, eleifend sollicitudin libero. Fusce ac venenatis erat, non molestie risus. In nec dui sed elit accumsan lacinia id ac mauris. <br><br>

  Morbi ut consectetur arcu, at commodo quam. Suspendisse vel lobortis libero. Curabitur eget scelerisque <strong style="font-family: serif; font-size: large;">E</strong>x. Phasellus ut nisi mattis, dignissim lectus vitae, dictum ligula. Sed vulputate metus a aliquet pulvinar. In sed ullamcorper libero. Sed arcu tellus, tempor pharetra massa ac, lacinia molestie dui. In at dolor consectetur, rutrum magna vitae, rhoncus tortor. Nulla facilisi. Quisque vel sagittis urna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce volutpat scelerisque enim. Aliquam dapibus justo eu pretium elementum. Pellentesque leo turpis, ornare in porta eget, iaculis vel orci. <br><br>

  Nulla at nunc malesuada, semper est vitae, ultrices sem. Etiam pulvinar quam nunc, ut sagittis nibh tempus a. Duis eu pellentesque leo, eget gravida elit. Proin maximus tincidunt est. Donec augue massa, efficitur id feugiat ac, suscipit et lorem. Duis elementum egestas urna vitae accumsan. Vestibulum eu lorem nibh. Curabitur pellentesque porttitor sem, a consequat e<strong style="font-family: serif; font-size: large;">X</strong> aliquam in. Nulla tincidunt pretium arcu eu porta. Integer fermentum lacus vel euismod viverra. Curabitur vitae fermentum augue, eget pellentesque dolor. Nunc tristique gravida metus, quis posuere purus eleifend nec. <br><br>

  Aenean dictum magna ut quam egestas vehicula. Integer non vestibulum dui, in gravida quam. Maecenas imperdiet rutrum leo, sagittis rhoncus risus viverra in. Vivamus facilisis scelerisque odio, vel fermentum nibh malesuada nec. Quisque interdum, erat et volutpat viverra, purus odio vulputate mi, non condimentum risus ante eget neque. Sed a luctus purus. Quisque id ipsum pretium, tristique ante vel, commodo tellus. Nulla porttitor ipsum eu lacus tempor scelerisque.
</template>